/**
 * types.ts - Type definitions for the mindmap memory system
 * @see docs/mindmap-design.md for specification
 */

/**
 * Link - directional connection from a node to another resource
 * Links are stubs that store metadata only (no resolution)
 */
export interface Link {
  /** Type of target: node in same mindmap, file, URL, or term */
  target_type: 'node' | 'file' | 'url' | 'term';
  /** Target node id (when target_type is 'node') */
  node_id?: string;
  /** Target file path (when target_type is 'file') */
  file_path?: string;
  /** Target URL (when target_type is 'url') */
  url?: string;
  /** The term name (when target_type is 'term'), e.g. "STAR principle" */
  term_name?: string;
  /** Comment describing this relationship */
  comment: string;
}

/**
 * Node - a single node in the mindmap tree
 */
export interface Node {
  /** 
   * The slash-separated "logic path" to a node, starting from root ('/')
   * e.g. "/skill/example/anti-pattern"
   */
  id: string;
  /** The original text of the markdown section */
  text: string;
  /** The node's title (extracted from heading) */
  title: string;
  /** The node's summary, generated by LLM using A-N-C-E context */
  summary: string;
  /** What level this node is at (root = 0, direct children = 1, etc.) */
  level: number;
  /** Direct child nodes */
  children: Node[];
  /** Outward links to other resources */
  links: Link[];
  /**
   * IN-MEMORY ONLY — never serialized to mindmap.json.
   * True if this node originates from mindmap.json (= MYCC.md isomorph).
   * Set to true by load_mindmap; set to false for patch-added nodes.
   * Drives compile (only is_mycc nodes get summaries) and rebuild logic.
   */
  is_mycc?: boolean;
  /**
   * IN-MEMORY ONLY — never serialized to mindmap.json.
   * True if this node was created or modified by a patch.
   * For 'add' patches: is_patch=true on the new node.
   * For 'update' patches: is_patch=true on the target (is_mycc preserved).
   * Drives rebuild: is_patch on an is_mycc node → emit 'update' to preserve patched text.
   */
  is_patch?: boolean;
}

/**
 * Mindmap - the complete agent memory structure
 * Dates are stored as ISO strings for JSON serialization
 */
export interface Mindmap {
  /** The backed resource folder */
  dir: string;
  /** Original markdown file path (relative to workDir) */
  source_file: string;
  /** Hash of the original markdown (for validation) */
  hash: string;
  /** Time of compilation (ISO string) */
  compiled_at: string;
  /** Time of last modification (ISO string) */
  updated_at: string;
  /** Root node of the tree */
  root: Node;
}

/**
 * Parsed section from markdown
 * Used during compilation to build the tree
 */
export interface MarkdownSection {
  level: number;
  title: string;
  text: string;
  children: MarkdownSection[];
}

/**
 * Context for A-N-C-E summarization
 * A = Ancestor texts, N = Node text, C = Child summaries, E = agent bEhavior
 */
export interface ANCEContext {
  /** A: all ancestor texts, combined */
  ancestors: string[];
  /** N: the text of the node itself */
  nodeText: string;
  /** C: all summaries of descendants (already computed) */
  descendantSummaries: string[];
  /** E: agent behavior context (e.g., PLAN mode behavior patterns) */
  agentBehavior?: string;
}

/**
 * Options for compile_mindmap
 */
export interface CompileOptions {
  /** Current working directory (for resolving relative paths) */
  cwd?: string;
  /** Custom hash algorithm (default: sha256) */
  hashAlgorithm?: 'sha256' | 'sha512' | 'md5';
}

/**
 * Options for patch_mindmap
 */
export interface PatchOptions {
  /** Optional feedback to incorporate into the summary */
  feedback?: string;
}

/**
 * A single patch action recorded in mindmap-patch.jsonl.
 * Each recap produces at most one patch action (add / update / delete).
 * Actions are replayed at startup to rebuild the in-memory merged tree.
 */
export interface MindmapPatchAction {
  /** Action type — exactly one per recap */
  action: 'add' | 'update' | 'delete';
  /** Target node path: parent for 'add', target for 'update'/'delete' */
  path: string;
  /** For 'add': the new child node's title */
  title?: string;
  /** For 'add'/'update': the new text content */
  text?: string;
  /**
   * For 'add': optional outbound links to attach to the new node.
   * Replayed onto the in-memory node by applyPatchAction so patch-added
   * nodes can carry term/file/url/node links — in particular `term` links,
   * which recall's collectDescendantTerms hoists to the root "Key Terms"
   * list. Without this field, patch-added nodes always enter the tree with
   * `links: []` and can never surface as Key Terms (no recompile needed).
   */
  links?: Link[];
  /** ISO timestamp of when the patch was created */
  timestamp: string;
  /** Checkpoint ID that triggered this patch */
  checkpoint_id: string;
  /** Brief reason for the change (from LLM) */
  reason: string;
  /** Hash of mindmap.json at the time of patch creation (for invalidation) */
  mindmap_hash: string;
}

/**
 * Result of get_node operation
 */
export interface GetNodeResult {
  node: Node | null;
  path: string[];
  error?: string;
}

/**
 * Hash generation result
 */
export interface HashResult {
  hash: string;
  algorithm: string;
}

/**
 * JSON representation of Mindmap for serialization
 * @deprecated Use Mindmap instead - dates are now stored as ISO strings
 */
export type MindmapJSON = Mindmap;
