/**
 * types.ts - Type definitions for the mindmap memory system
 * @see docs/mindmap-design.md for specification
 */

/**
 * Link - directional connection from a node to another resource
 * Links are stubs that store metadata only (no resolution)
 */
export interface Link {
  /** Type of target: node in same mindmap, file, or URL */
  target_type: 'node' | 'file' | 'url';
  /** Target node id (when target_type is 'node') */
  node_id?: string;
  /** Target file path (when target_type is 'file') */
  file_path?: string;
  /** Target URL (when target_type is 'url') */
  url?: string;
  /** Comment describing this relationship */
  comment: string;
}

/**
 * Node - a single node in the mindmap tree
 */
export interface Node {
  /** 
   * The slash-separated "logic path" to a node, starting from root ('/')
   * e.g. "/skill/example/anti-pattern"
   */
  id: string;
  /** The original text of the markdown section */
  text: string;
  /** The node's title (extracted from heading) */
  title: string;
  /** The node's summary, generated by LLM using A-N-C-E context */
  summary: string;
  /** What level this node is at (root = 0, direct children = 1, etc.) */
  level: number;
  /** Direct child nodes */
  children: Node[];
  /** Outward links to other resources */
  links: Link[];
}

/**
 * Mindmap - the complete agent memory structure
 * Dates are stored as ISO strings for JSON serialization
 */
export interface Mindmap {
  /** The backed resource folder */
  dir: string;
  /** Original markdown file path (relative to workDir) */
  source_file: string;
  /** Hash of the original markdown (for validation) */
  hash: string;
  /** Time of compilation (ISO string) */
  compiled_at: string;
  /** Time of last modification (ISO string) */
  updated_at: string;
  /** Root node of the tree */
  root: Node;
}

/**
 * Parsed section from markdown
 * Used during compilation to build the tree
 */
export interface MarkdownSection {
  level: number;
  title: string;
  text: string;
  children: MarkdownSection[];
}

/**
 * Context for A-N-C-E summarization
 * A = Ancestor texts, N = Node text, C = Child summaries, E = agent bEhavior
 */
export interface ANCEContext {
  /** A: all ancestor texts, combined */
  ancestors: string[];
  /** N: the text of the node itself */
  nodeText: string;
  /** C: all summaries of descendants (already computed) */
  descendantSummaries: string[];
  /** E: agent behavior context (e.g., PLAN mode behavior patterns) */
  agentBehavior?: string;
}

/**
 * Options for compile_mindmap
 */
export interface CompileOptions {
  /** Current working directory (for resolving relative paths) */
  cwd?: string;
  /** Custom hash algorithm (default: sha256) */
  hashAlgorithm?: 'sha256' | 'sha512' | 'md5';
}

/**
 * Options for patch_mindmap
 */
export interface PatchOptions {
  /** Optional feedback to incorporate into the summary */
  feedback?: string;
}

/**
 * Result of get_node operation
 */
export interface GetNodeResult {
  node: Node | null;
  path: string[];
  error?: string;
}

/**
 * Hash generation result
 */
export interface HashResult {
  hash: string;
  algorithm: string;
}

/**
 * JSON representation of Mindmap for serialization
 * @deprecated Use Mindmap instead - dates are now stored as ISO strings
 */
export type MindmapJSON = Mindmap;
