/**
 * esc-wrap-up.ts - Quick-return ESC wrap-up state management
 *
 * When ESC is pressed during an LLM call, the prompt should show immediately
 * while the LLM wrap-up continues in background. The wrap-up appears as a
 * letter-box above the prompt when complete.
 *
 * Architecture (redesigned to avoid triologue parity issues):
 *
 * 1. ESC pressed → startWrapUp() calls triologue.beginWrapUp()
 *    - Adds [WRAP_UP] user message inline to triologue (never combined)
 *    - Background LLM call runs to get wrap-up content
 *    - Returns immediately so prompt shows ASAP
 *
 * 2. Wrap-up LLM completes → Promise resolves in background
 *    - Calls triologue.finishWrapUp(content) to add agent response inline
 *    - Stores content + completion timestamp for letter-box display
 *
 * 3. User submits next query → in prompt.ts:
 *    - If wrap-up completed AND past 3s grace period:
 *      → triologue.commitWrapUp() — permanently keep the wrap-up turn
 *    - If wrap-up not completed OR within 3s:
 *      → triologue.rollbackWrapUp() — remove wrap-up messages via truncation
 *
 * Key benefit: No message snapshot. The wrap-up turn is always in the triologue
 * at the correct position. rollbackWrapUp() is a simple array .length truncation,
 * instant and race-free.
 */

import { displayLetterBox } from '../utils/letter-box.js';
import type { Triologue } from './triologue.js';
import type { LineEditor } from '../utils/line-editor.js';
import { retryChat, MODEL } from '../engine/chat-provider.js';
import { getApiProvider } from '../config.js';
import { getServeHub } from '../serve/serve-registry.js';
import {
  beginWrapUpState,
  settleWrapUp,
  getWrapUpState,
  hasPendingWrapUp,
  markWrapUpShown,
} from './wrap-up-state.js';
import type { Tool } from 'ollama';
// NOTE: The wrap-up LIFECYCLE STATE (the `wrapUpState` singleton, its accessors
// getWrapUpState/hasPendingWrapUp/markWrapUpShown/clearWrapUp, the
// WRAP_UP_GRACE_PERIOD_MS constant and the pure evaluateWrapUp() policy) now
// lives in src/loop/wrap-up-state.ts (review gate A5 facet separation + import-
// cycle avoidance). This file keeps only the LLM orchestration below. Do NOT
// re-export the moved symbols from here — importers point at wrap-up-state.js
// directly.

/**
 * Run the wrap-up LLM call.
 * Uses triologue.getMessages() which INCLUDES the WRAP_UP note added by
 * beginWrapUp() — always fresh, no snapshot needed.
 *
 * For DeepSeek: keeps the full tool list so the model has context, but sets
 * tool_choice='none' to prevent tool calls (avoids raw XML in content).
 * For Ollama: passes empty tools list (unchanged behavior).
 */
async function runWrapUpLLM(triologue: Triologue, tools?: Tool[]): Promise<string> {
  const messages = triologue.getMessages();
  const isDeepseek = getApiProvider() === 'deepseek';

  try {
    const response = isDeepseek
      ? await retryChat(
          {
            model: MODEL,
            messages,
            tools: tools || [],
            think: true,
            toolChoice: 'none',
          } as Parameters<typeof retryChat>[0],
          { noSpinner: true },
        )
      : await retryChat(
          {
            model: MODEL,
            messages,
            tools: [],
            think: true,
          },
          { noSpinner: true },
        );

    return response.message?.content || '';
  } catch {
    return '';
  }
}

/**
 * Start tracking a background wrap-up operation.
 * Calls triologue.beginWrapUp() to add WRAP_UP note inline.
 * Runs the LLM wrap-up in background.
 */
export function startWrapUp(triologue: Triologue, tools?: Tool[]): void {
  // Add WRAP_UP user message inline (always separate, never combined)
  triologue.beginWrapUp();

  const promise = runWrapUpLLM(triologue, tools);
  // Attach the fresh in-flight capsule in wrap-up-state.ts (A5: state lives
  // there, orchestration here). Object replacement keeps .then stale-guards
  // working exactly as before a restart of the window.
  beginWrapUpState(promise, triologue);

  promise.then((content) => {
    // Stale-guard + settle are encapsulated in settleWrapUp(): only the live
    // promise settles, and settling NULLS the promise so isWrapUpInFlight()
    // goes false the moment the wrap-up LLM completes (review gate A1 — the
    // hub's wake seam reads exactly this signal).
    if (!settleWrapUp(promise, content)) return;

    if (content) {
      // Try to add agent response.
      // If triologue was already rolled back (user submitted quickly),
      // finishWrapUp is a no-op (wrapUpMark === -1).
      triologue.finishWrapUp(content);
      // SERVE (WebUI) completion trigger: the terminal ask() path that calls
      // tryDisplayWrapUp is NEVER entered while serve is running (web-input-
      // provider.ts getInput() routes straight to hub.waitForInput(), bypassing
      // the LineEditor/ask() block). So without this, the wrap-up generated by
      // the background LLM is silently dropped in serve mode — the WebUI chat
      // freezes after the last bubble (the 停止/Stop-button hang). Deliver it the
      // moment the background LLM finishes: displayLetterBox mirrors it to the
      // WebUI via resultCallback → hub.broadcast. markWrapUpShown makes a later
      // tryDisplayWrapUp(null) (belt-and-suspenders in web-input-provider) a
      // no-op, so double-display is impossible.
      if (getServeHub().isRunning()) {
        markWrapUpShown();
        displayLetterBox(content);
      }
    }
    // Wake seam (A1, plan §5 instant 3 of 3): the wrap-up window just CLOSED
    // (settleWrapUp nulled the promise regardless of content). A steering
    // note that arrived DURING the window was HELD by takeForDelivery at the
    // write-point; deliver it now to the already-armed PROMPT wait. DIRECT
    // gated hub call — no callback registration (binding constraint); the
    // isRunning() gate keeps a settle racing a terminal stop() inert (the
    // A2 fallback wipe owns the queue then). Safe on empty queue: no-op.
    if (getServeHub().isRunning()) {
      getServeHub().onWrapUpSettled();
    }
  }).catch(() => {
    // Failed wrap-up: record empty content + completion timestamp (rolled
    // back by evaluateWrapUp), settling the window the same way. Settle
    // FIRST — the WAKE seam must observe the window CLOSED (promise nulled),
    // otherwise takeForDelivery still sees wrapUpInFlight=true and the flush
    // no-ops, stranding a held note behind a wrap-up LLM that just errored.
    settleWrapUp(promise, '');
    // Wake seam (A1): same direct gated hub call as the success path. Fired
    // even when settled===false (stale capsule): if a newer capsule is in
    // flight its own then/catch owns the wake and takeForDelivery no-ops on
    // wrapUpInFlight; if no newer capsule exists the window is genuinely
    // closed and this is the only wake a pre-settle held note will get.
    if (getServeHub().isRunning()) {
      getServeHub().onWrapUpSettled();
    }
  });
}

/**
 * Display wrap-up content in letter-box format
 * Shows the wrap-up above the current line-editor prompt
 */
export function displayWrapUp(content: string): void {
  if (content && content.trim()) {
    displayLetterBox(content);
  }
}

/**
 * Try to display a pending wrap-up above the given editor.
 * If wrap-up content is ready, clears the editor from screen,
 * displays the letter-box, and re-renders the editor below it.
 * Returns true if the wrap-up was shown, false otherwise.
 *
 * SERVE (WebUI) MODE: there is no `LineEditor` (the WebUI routes input through
 * `ServeHub.waitForCardResponse`, so `agent-io.activeLineEditor` is null). The
 * old code bailed out on a null editor and SILENTLY DROPPED the wrap-up — it was
 * generated by the background LLM but never broadcast, so the WebUI chat froze
 * after the last bubble (the 停止/Stop-button hang). When serve is running we
 * deliver the wrap-up directly via `displayLetterBox`, which mirrors it to the
 * WebUI through `resultCallback` → `hub.broadcast(...)`. This branch does NOT
 * depend on the `editor` argument.
 */
export function tryDisplayWrapUp(editor: LineEditor | null): boolean {
  if (!hasPendingWrapUp()) return false;
  const { content } = getWrapUpState();
  if (!content || !content.trim()) return false;
  // SERVE mode: no LineEditor, but the WebUI is reachable via displayLetterBox's
  // resultCallback (wired in src/serve/activate.ts). Deliver directly.
  if (getServeHub().isRunning()) {
    markWrapUpShown();
    displayLetterBox(content);
    return true;
  }
  // Terminal mode: requires a LineEditor to clear/redraw around the letter-box.
  if (!editor) return false;
  markWrapUpShown();
  editor.prepareForExternalContentAbove();
  displayWrapUp(content);
  editor.rerender();
  return true;
}
