/**
 * read-handlers.ts - Pluggable file-type handler dispatch for read_file
 *
 * A FileHandler post-processes file content before it is returned to the LLM
 * (and optionally displayed to the terminal via the `aloud` parameter).
 * Handlers are matched by content (with a suffix quick-check at the top of
 * `matches`), not by file name alone — this keeps matching robust against
 * renamed/copied files while staying cheap (suffix check avoids parsing every
 * file).
 *
 * Handler dispatch is extensible: future handlers (e.g. diagram-md-handler
 * that filters large ```diagram code blocks, channel-file-handler that
 * surfaces peer info from channel JSON) register here without touching
 * read_file itself.
 *
 * Result contract:
 * - toolResult: returned to the LLM as the read_file tool result.
 * - displayText: shown to the terminal via brief when aloud=true.
 *
 * For the crossroad replay-bypass use case, the crossroad-json-handler merges
 * prefix + continuation into displayText and returns only a short confirmation
 * as toolResult — so the full content reaches the terminal WITHOUT being
 * regenerated by the LLM, which keeps it outside detectTurningWord's scan
 * scope (it only scans chat.assistantContent, the LLM's own text output).
 */

/**
 * Result of a FileHandler.process call.
 */
export interface FileHandlerResult {
  /** Returned to the LLM as the read_file tool result. */
  toolResult: string;
  /** Displayed to the terminal via brief when aloud=true. */
  displayText: string;
}

/**
 * A pluggable handler that post-processes file content for read_file.
 *
 * matches() should start with a cheap suffix quick-check (e.g.
 * `if (!filePath.endsWith('.json')) return false;`) before doing any
 * content inspection, so non-matching files incur no parse cost.
 */
export interface FileHandler {
  /**
   * Whether this handler applies to the given file. Begin with a suffix
   * quick-check, then inspect content features.
   */
  matches(filePath: string, content: string): boolean;
  /**
   * Process the file content. Called only when matches() returned true.
   */
  process(filePath: string, content: string): FileHandlerResult;
}

import { crossroadJsonHandler } from './read-handlers/crossroad-json-handler.js';

/**
 * Handler registry. Handlers are tried in registration order; the first
 * whose matches() returns true wins.
 */
export const fileHandlers: FileHandler[] = [
  crossroadJsonHandler,
];